version: '2.0'

networks:
  cd-tools-network-blue:
    driver: bridge

services:
  sonarqubedb-blue:
    image: postgres
    container_name: sonarqube-db-blue
    networks:
      - cd-tools-network-blue
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /volumes/postgres/data:/var/lib/postgresql/data

  sonarqube-blue:
    image: sonarqube:6.4
    container_name: sonarqube-blue
    command: -Dsonar.web.context=/sonarqube
    ports:
      - "9000:9000"
      - "5432:5432"
    networks:
      - cd-tools-network-blue
    depends_on:
      - sonarqubedb-blue
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqubedb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  artifactory-blue:
    image: docker.bintray.io/jfrog/artifactory-oss:5.5.2
    container_name: artifactory-blue
    networks:
      - cd-tools-network-blue
    ports:
     - 8181:8081
    environment:
     - ADMIN_PASSWORD=password
    volumes:
     - /volumes/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
#    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  jenkins-blue:
    build: ./jenkins
    container_name: jenkins-blue
    ports:
      - "8180:8080"
    command: --prefix=/jenkins/
    networks:
      - cd-tools-network-blue
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /volumes/jenkins/:/var/lib/jenkins/
    depends_on:
      - sonarqube-blue
      - artifactory-blue
    environment:
      - SONARQUBE_SERVER=http://sonarqube-blue:9000/sonarqube
      - ARTIFACTORY_SERVER=http://artifactory-blue:8181

  nginx-blue:
    build: ./nginx-blue
    container_name: nginx-blue
    ports:
      - "8100:80"
      - "843:443"
    networks:
      - cd-tools-network-blue
    depends_on:
      - jenkins-blue
      - sonarqube-blue
      - artifactory-blue

  runtime:
    build: ./runtime
    container_name: runtime-blue
    networks:
      - cd-tools-network-blue
    depends_on:
      - jenkins-blue
      - sonarqube-blue
      - artifactory-blue
      - nginx-blue

