version: '2.0'

networks:
  cd-tools-network-green:
    driver: bridge

services:
  artifactory-green:
    image: docker.bintray.io/jfrog/artifactory-oss:5.5.2
    container_name: artifactory-green
    networks:
      - cd-tools-network-green
    ports:
     - 8081:8081
    environment:
     - ADMIN_PASSWORD=password
    volumes:
     - /volumes/artifactory-green:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
#    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  jenkins-green:
    build: ./jenkins
    container_name: jenkins-green
    ports:
      - "8080:8080"
    command: --prefix=/jenkins/
    networks:
      - cd-tools-network-green
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /volumes/jenkins-green/:/var/lib/jenkins/
    depends_on:
      - artifactory-green
    environment:
      - ARTIFACTORY_SERVER=http://artifactory-green:8081

  nginx-gren:
    build: ./nginx-gren
    container_name: nginx-gren
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cd-tools-network-green
    depends_on:
      - jenkins-green
      - artifactory-green

  runtime-green:
    build: ./runtime
    container_name: runtime-green
    networks:
      - cd-tools-network-green
    depends_on:
      - jenkins-green
      - artifactory-green
      - nginx-gren

