sudo docker pull docker.bintray.io/jfrog/artifactory-oss:5.5.2
sudo docker pull jenkins/jenkins:latest
sudo docker pull nginx
sudo docker pull alpine
sudo docker pull docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.1
sudo docker pull docker.elastic.co/kibana/kibana:6.2.1
sudo docker pull docker.elastic.co/logstash/logstash:6.2.1
sudo docker pull docker.elastic.co/beats/filebeat:6.2.1
sudo docker pull centos:7
sudo docker pull maven:3-alpine
